# Generated by Django 3.0.7 on 2020-07-29 09:01

import clicknetapp.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='iptable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=500)),
                ('cookie', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='noti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36)),
                ('body', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='usertab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_block', models.BooleanField(default=False)),
                ('refercode', models.CharField(max_length=500)),
                ('referredby', models.CharField(max_length=500, null=True)),
                ('img', models.ImageField(default='user_img/default.png', upload_to='user_img')),
            ],
        ),
        migrations.CreateModel(
            name='userurltable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=400)),
                ('shorturl', models.URLField(max_length=5000, null=True)),
                ('click', models.IntegerField(default=0)),
                ('earning', models.FloatField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clicknetapp.usertab')),
            ],
        ),
        migrations.CreateModel(
            name='useraddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('adr', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('zip', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clicknetapp.usertab')),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clicknetapp.usertab')),
            ],
        ),
        migrations.CreateModel(
            name='statictab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=clicknetapp.models.statictab.indiantime)),
                ('click', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clicknetapp.usertab')),
            ],
        ),
        migrations.CreateModel(
            name='static',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=clicknetapp.models.static.indiantime)),
                ('click', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clicknetapp.usertab')),
            ],
        ),
        migrations.CreateModel(
            name='redeemtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paddress', models.CharField(max_length=120)),
                ('ifsc', models.CharField(max_length=120, null=True)),
                ('amount', models.CharField(max_length=120)),
                ('redeem_date', models.DateTimeField(default=clicknetapp.models.redeemtable.indiantime)),
                ('status', models.IntegerField(default=0)),
                ('paymentmode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clicknetapp.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clicknetapp.usertab')),
            ],
        ),
        migrations.CreateModel(
            name='password_change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clicknetapp.usertab')),
            ],
        ),
        migrations.CreateModel(
            name='balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blc', models.FloatField(default=0)),
                ('referblc', models.FloatField(default=0)),
                ('referbyblc', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clicknetapp.usertab')),
            ],
        ),
    ]
