# Generated by Django 2.1.5 on 2019-01-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0002_auto_20190125_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noti',
            name='title',
            field=models.CharField(max_length=36),
        ),
    ]
