# Generated by Django 2.1.5 on 2019-01-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0004_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='balance',
            name='blc',
            field=models.IntegerField(),
        ),
    ]
