# Generated by Django 2.1.5 on 2019-01-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0005_auto_20190125_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='userurltable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=400)),
            ],
        ),
    ]
