# Generated by Django 2.1 on 2019-01-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0007_redeemtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemtable',
            name='paddress',
            field=models.CharField(default=7415251523, max_length=120),
            preserve_default=False,
        ),
    ]
