# Generated by Django 2.1 on 2019-01-31 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clicknetapp', '0008_redeemtable_paddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='useraddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('adr', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('zip', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('user', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
