# Generated by Django 2.1 on 2019-02-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0009_useraddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='codetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150)),
            ],
        ),
    ]
