# Generated by Django 2.1 on 2019-02-02 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clicknetapp', '0010_codetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userurltable',
            name='shorturl',
            field=models.URLField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='userurltable',
            name='user',
            field=models.ForeignKey(null=True, on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
