# Generated by Django 2.1 on 2019-02-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0011_auto_20190202_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='iptable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='userurltable',
            name='click',
            field=models.IntegerField(null=True),
        ),
    ]
