# Generated by Django 2.1 on 2019-02-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0012_auto_20190203_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userurltable',
            name='click',
            field=models.IntegerField(default=0),
        ),
    ]
