# Generated by Django 2.1 on 2019-02-03 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0013_auto_20190203_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptable',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
