# Generated by Django 2.1 on 2019-02-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0014_iptable_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iptable',
            name='created_date',
        ),
    ]
