# Generated by Django 2.1 on 2019-02-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0016_iptable_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptable',
            name='cookie',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
