# Generated by Django 2.1 on 2019-02-09 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0017_iptable_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemtable',
            name='redeem_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='redeemtable',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
