# Generated by Django 2.1 on 2019-02-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0018_auto_20190209_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemtable',
            name='paymentmode',
            field=models.ForeignKey(on_delete=True, to='clicknetapp.payment'),
        ),
    ]
