# Generated by Django 2.1 on 2019-02-09 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0019_auto_20190209_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemtable',
            name='redeem_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 9, 22, 58, 40, 203142, tzinfo=utc)),
        ),
    ]
