# Generated by Django 2.1 on 2019-02-09 17:47

import clicknetapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0020_auto_20190209_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemtable',
            name='redeem_date',
            field=models.DateTimeField(default=clicknetapp.models.redeemtable.indiantime),
        ),
    ]
