# Generated by Django 2.1 on 2019-02-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0021_auto_20190209_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='userurltable',
            name='earning',
            field=models.IntegerField(default=0),
        ),
    ]
