# Generated by Django 2.1 on 2019-02-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0022_userurltable_earning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userurltable',
            name='earning',
            field=models.FloatField(default=0),
        ),
    ]
