# Generated by Django 2.1 on 2019-02-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0024_auto_20190210_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemtable',
            name='status',
            field=models.IntegerField(),
        ),
    ]
