# Generated by Django 2.1 on 2019-02-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0025_auto_20190212_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemtable',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
