# Generated by Django 2.1 on 2019-02-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0027_usertab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(on_delete=True, to='clicknetapp.usertab'),
        ),
        migrations.AlterField(
            model_name='redeemtable',
            name='user',
            field=models.ForeignKey(on_delete=True, to='clicknetapp.usertab'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(on_delete=True, to='clicknetapp.usertab'),
        ),
        migrations.AlterField(
            model_name='userurltable',
            name='user',
            field=models.ForeignKey(null=True, on_delete=True, to='clicknetapp.usertab'),
        ),
    ]
