# Generated by Django 2.1 on 2019-02-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0028_auto_20190214_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertab',
            name='referredby',
            field=models.IntegerField(default=0),
        ),
    ]
