# Generated by Django 2.1 on 2019-02-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0029_auto_20190214_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='referblc',
            field=models.FloatField(default=0),
        ),
    ]
