# Generated by Django 2.1 on 2019-02-16 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0030_balance_referblc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertab',
            name='referredby',
        ),
    ]
