# Generated by Django 2.1 on 2019-02-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0031_remove_usertab_referredby'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertab',
            name='referredbu',
            field=models.IntegerField(default=1),
        ),
    ]
