# Generated by Django 2.1 on 2019-02-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0032_usertab_referredbu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertab',
            old_name='referredbu',
            new_name='referredby',
        ),
    ]
