# Generated by Django 2.1 on 2019-02-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0033_auto_20190216_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertab',
            name='referredby',
            field=models.IntegerField(null=True),
        ),
    ]
