# Generated by Django 2.1 on 2019-02-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0035_refertable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertab',
            name='referredby',
        ),
    ]
