# Generated by Django 2.1 on 2019-02-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0036_remove_usertab_referredby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refertable',
            name='referredby',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='refertable',
            name='user',
            field=models.ForeignKey(on_delete=True, to='clicknetapp.usertab'),
        ),
    ]
