# Generated by Django 2.1 on 2019-02-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0037_auto_20190216_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refertable',
            name='referredby',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
