# Generated by Django 2.1 on 2019-02-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0039_auto_20190216_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertab',
            name='refercode',
            field=models.CharField(default=1, max_length=500),
        ),
    ]
