# Generated by Django 2.1 on 2019-02-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0040_usertab_refercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertab',
            name='referredby',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
