# Generated by Django 2.1 on 2019-02-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0041_auto_20190219_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertab',
            name='refercode',
            field=models.CharField(max_length=500),
        ),
    ]
