# Generated by Django 2.1 on 2019-02-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0042_auto_20190219_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='referbyblc',
            field=models.FloatField(default=0),
        ),
    ]
