# Generated by Django 2.1 on 2019-02-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0043_balance_referbyblc'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertab',
            name='img',
            field=models.ImageField(blank=True, upload_to='user_img'),
        ),
    ]
