# Generated by Django 2.1 on 2019-02-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0045_auto_20190222_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertab',
            name='img',
            field=models.ImageField(default='user_img/default.png', upload_to='user_img'),
        ),
    ]
