# Generated by Django 2.1 on 2019-02-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0046_auto_20190222_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertab',
            name='img',
            field=models.ImageField(blank=True, default='user_img/default.png', upload_to='user_img'),
        ),
    ]
