# Generated by Django 2.1 on 2019-02-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0048_auto_20190223_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertab',
            name='img',
            field=models.ImageField(default='user_img/default.png', upload_to='user_img'),
        ),
    ]
