# Generated by Django 2.1.5 on 2019-03-03 10:03

import clicknetapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0051_statictab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statictab',
            name='date',
            field=models.DateField(default=clicknetapp.models.statictab.indiantime),
        ),
    ]
