# Generated by Django 2.1.5 on 2019-03-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0052_auto_20190303_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertab',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
