# Generated by Django 2.1.5 on 2019-03-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0053_usertab_is_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemtable',
            name='ifsc',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
