# Generated by Django 2.1.5 on 2019-03-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicknetapp', '0054_redeemtable_ifsc'),
    ]

    operations = [
        migrations.CreateModel(
            name='password_change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=True, to='clicknetapp.usertab')),
            ],
        ),
    ]
